import type { AgentRun, Cycle, GraphNode, Project } from "@/lib/api";

export const cycle: Cycle = {
  id: "cyc-1",
  project_id: "proj-1",
  status: "awaiting_agents",
  provider: "local-simulation",
  round: 3,
  branch: "main",
  brief: "Improve GB1 thermal stability",
  acu_limit: 900,
  acus_used: 412,
  orchestrator_session_url: "https://app.devin.ai/sessions/abc",
  plan: {
    strategy: "stability sweep then re-score docking",
    workflow_tools: { alphafold: "auto", proteinmpnn: "required" },
    workflow: {
      policies: { alphafold: "auto", proteinmpnn: "required" },
      runs: [
        {
          tool: "alphafold",
          target: "working",
          status: "finished",
          reason: "verified PDB stored",
        },
      ],
    },
    agents: [
      { role: "sequence", task: "Propose sequence-level designs." },
      { role: "literature", task: "Pull stability references." },
    ],
  },
};

export const agents: AgentRun[] = [
  {
    id: "run-orch",
    role: "orchestrator",
    task: "Plan round 3 and fan out",
    provider: "local-simulation",
    status: "running",
    tags: ["cycle"],
    attempts: 1,
    acus: 146,
    acu_limit: 200,
    log: [{ at: "2026-08-22T12:04:02Z", message: "fanned out 4 children" }],
  },
  {
    id: "run-lit",
    role: "literature",
    task: "Pull stability references",
    provider: "local-simulation",
    status: "finished",
    devin_session_url: "https://app.devin.ai/sessions/lit",
    tags: [],
    attempts: 1,
    acus: 61,
    acu_limit: 80,
    log: [{ at: "2026-08-22T12:04:31Z", message: "pulled 6 GB1 stability refs" }],
  },
  {
    id: "run-seq",
    role: "sequence",
    task: "Propose sequence-level designs",
    provider: "local-simulation",
    status: "failed",
    tags: [],
    attempts: 2,
    acus: 118,
    acu_limit: 120,
    error: "toolkit rejected proposal",
    log: [],
  },
  {
    id: "run-rank",
    role: "ranking",
    task: "Rank candidates and build the wet-lab pack",
    provider: "local-simulation",
    status: "pending",
    tags: [],
    attempts: 1,
    acus: 0,
    acu_limit: 40,
    log: [],
  },
];

export const nodes: GraphNode[] = [
  {
    id: "commit-12",
    short_id: "a1b2c3d",
    label: "GB1-v12",
    branch: "main",
    agent_role: "sequence",
    provider: "local-simulation",
    mutations: ["T2I", "N8D"],
    scores: { composite_score: 0.842 },
    passed_filters: true,
    failed_filters: [],
    cycle_round: 3,
    is_head: true,
  },
  {
    id: "commit-8",
    short_id: "9f8e7d6",
    label: "GB1-v8",
    branch: "stability",
    agent_role: "structure",
    provider: "local-simulation",
    mutations: ["K10R"],
    scores: { composite_score: 0.781 },
    passed_filters: false,
    failed_filters: ["aggregation"],
    cycle_round: 2,
    is_head: false,
  },
];

export const project: Project = {
  id: "proj-1",
  name: "GB1 stability",
  goal: "Improve GB1 thermal stability",
  target_name: "IgG Fc",
  target_sequence: "MKTAYIAKQRQISFVKSHFSRQLEERLGLIEVQ",
  is_demo: true,
  commit_count: 12,
  cycle_count: 3,
  branches: ["main", "stability"],
  head_commit_id: "commit-9",
};
