"""IND-style dossier assembly.

The dossier mirrors the section structure of a US IND / CTD module 2 summary so a human
reviewer can find things where they expect them. Every section reports its own completeness
and the provenance of its content, and predicted values are labelled as predictions.

This is a *draft package for human review*. It is not a regulatory submission, it contains no
GLP-compliant study reports, and predicted properties are not evidence of human safety.
"""

from __future__ import annotations

from datetime import UTC, datetime

DISCLAIMER = (
    "Draft package generated by an autonomous system. Deterministic in-silico predictions are "
    "ranking hypotheses, not measured data; no GLP study, no human exposure and no regulatory "
    "review is represented here. Sections marked 'predicted' require experimental confirmation "
    "before any filing."
)

SECTIONS: tuple[tuple[str, str], ...] = (
    ("summary", "Program summary and development rationale"),
    ("target", "Target rationale and disease hypothesis"),
    ("candidate", "Drug substance: identity and physicochemical properties"),
    ("pharmacology", "Nonclinical pharmacology (primary and selectivity)"),
    ("dmpk", "Pharmacokinetics and metabolism"),
    ("toxicology", "Toxicology and safety pharmacology"),
    ("cmc", "Chemistry, manufacturing and controls"),
    ("clinical", "Proposed clinical plan and first-in-human design"),
    ("ip", "Intellectual property position"),
    ("evidence", "Experimental evidence and prediction drift"),
)


def build_dossier(
    *,
    program: dict,
    candidate: dict | None,
    backup: dict | None = None,
    assays: list[dict] | None = None,
    gate_history: list[dict] | None = None,
    findings: dict | None = None,
    drift: dict | None = None,
    economics: dict | None = None,
) -> dict:
    """Assemble the dossier and score its completeness section by section."""
    assays = assays or []
    gate_history = gate_history or []
    findings = findings or {}
    sections: dict[str, dict] = {}

    sections["summary"] = _section(
        content={
            "program": program.get("name"),
            "target": program.get("target_name"),
            "indication": program.get("indication"),
            "stage": program.get("stage"),
            "autonomy_level": program.get("autonomy_level"),
            "objective": program.get("objective"),
            "gate_decisions": [
                {"stage": g.get("stage"), "decision": g.get("decision"), "score": g.get("score")}
                for g in gate_history
            ],
        },
        complete=bool(program.get("name") and program.get("target_name")),
        provenance="program record",
    )
    sections["target"] = _section(
        content={
            "evidence_score": findings.get("target_evidence_score"),
            "druggability_score": findings.get("druggability_score"),
            "narrative": findings.get("target_narrative"),
            "citations": findings.get("citations") or [],
        },
        complete=bool(findings.get("target_evidence_score") and findings.get("citations")),
        provenance="literature agent (cited) + deterministic pocket descriptors",
    )
    sections["candidate"] = _section(
        content=_candidate_identity(candidate, backup),
        complete=candidate is not None,
        provenance="content-addressed molecule commit + deterministic descriptors",
    )
    sections["pharmacology"] = _section(
        content={
            "binding": (candidate or {}).get("binding"),
            "selectivity": (candidate or {}).get("selectivity"),
            "prediction_basis": "complementarity proxy, no docked pose or free-energy calculation",
        },
        complete=bool((candidate or {}).get("binding")),
        provenance="predicted (in-silico proxy)",
    )
    sections["dmpk"] = _section(
        content={
            "admet": (candidate or {}).get("admet"),
            "dose_projection": (candidate or {}).get("dose_projection"),
        },
        complete=bool((candidate or {}).get("dose_projection")),
        provenance="predicted (physchem heuristics + one-compartment PK)",
    )
    sections["toxicology"] = _section(
        content={
            "liabilities": (candidate or {}).get("liabilities"),
            "toxicity_panel": ((candidate or {}).get("admet") or {}).get("toxicity"),
            "required_studies": [
                "GLP repeat-dose toxicity (rodent + non-rodent)",
                "Safety pharmacology core battery (CNS, cardiovascular, respiratory)",
                "In-vitro genotoxicity battery (Ames, micronucleus)",
            ],
        },
        complete=bool(((candidate or {}).get("admet") or {}).get("toxicity")),
        provenance="predicted (structural alerts + heuristics); GLP studies outstanding",
    )
    sections["cmc"] = _section(
        content={
            "synthesis": (candidate or {}).get("synthesis"),
            "scale_up_feasibility": findings.get("scale_up_feasibility"),
        },
        complete=bool((candidate or {}).get("synthesis")),
        provenance="fragment/complexity heuristic route estimate",
    )
    sections["clinical"] = _section(
        content={
            "plan": findings.get("clinical_plan"),
            "starting_dose_mg": findings.get("starting_dose_mg"),
            "starting_dose_basis": findings.get("starting_dose_basis"),
            "stopping_rules": findings.get("stopping_rules") or [],
        },
        complete=bool(findings.get("starting_dose_mg") and findings.get("stopping_rules")),
        provenance="clinical strategy agent proposal",
    )
    sections["ip"] = _section(
        content={
            "freedom_to_operate": findings.get("freedom_to_operate"),
            "claim_strategy": findings.get("claim_strategy"),
            "prior_art": findings.get("prior_art") or [],
        },
        complete=findings.get("freedom_to_operate") is not None,
        provenance="IP agent assessment (not a legal opinion)",
    )
    sections["evidence"] = _section(
        content={
            "assays": assays,
            "assay_count": len(assays),
            "prediction_drift": drift,
        },
        complete=bool(assays),
        provenance="ingested experimental results",
    )

    completeness = round(sum(1 for s in sections.values() if s["complete"]) / len(SECTIONS), 3)
    return {
        "generated_at": datetime.now(UTC).isoformat(),
        "disclaimer": DISCLAIMER,
        "program": program.get("name"),
        "completeness": completeness,
        "missing_sections": [k for k, s in sections.items() if not s["complete"]],
        "sections": {
            key: {"title": title, **sections[key]} for key, title in SECTIONS if key in sections
        },
        "economics": economics,
    }


def _candidate_identity(candidate: dict | None, backup: dict | None) -> dict:
    if not candidate:
        return {"status": "no candidate selected"}
    out = {
        "smiles": candidate.get("smiles"),
        "molecule_hash": candidate.get("molecule_hash"),
        "scaffold_key": candidate.get("scaffold_key"),
        "formula": candidate.get("formula"),
        "descriptors": candidate.get("descriptors"),
        "composite_score": candidate.get("composite_score"),
    }
    if backup:
        out["backup"] = {
            "smiles": backup.get("smiles"),
            "molecule_hash": backup.get("molecule_hash"),
            "composite_score": backup.get("composite_score"),
        }
    return out


def _section(*, content: object, complete: bool, provenance: str) -> dict:
    return {"content": content, "complete": bool(complete), "provenance": provenance}


def dossier_markdown(dossier: dict) -> str:
    """Render the dossier as a reviewable markdown document."""
    lines = [
        f"# IND-style draft dossier — {dossier.get('program') or 'unnamed program'}",
        "",
        f"> {dossier['disclaimer']}",
        "",
        f"Generated: {dossier['generated_at']}  |  Completeness: {dossier['completeness']:.0%}",
        "",
    ]
    for section in dossier["sections"].values():
        status = "complete" if section["complete"] else "INCOMPLETE"
        lines += [
            f"## {section['title']}",
            "",
            f"*Status: {status}. Provenance: {section['provenance']}.*",
            "",
            "```json",
            _pretty(section["content"]),
            "```",
            "",
        ]
    if dossier.get("economics"):
        lines += ["## Program economics", "", "```json", _pretty(dossier["economics"]), "```", ""]
    return "\n".join(lines)


def _pretty(value: object) -> str:
    import json

    return json.dumps(value, indent=2, sort_keys=True, default=str)
